FROM node:22-bullseye-slim

# 1. Установка системных зависимостей для Playwright
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Установка Yarn и Playwright глобально
RUN npm install -g yarn playwright && \
    npx playwright install --with-deps

# 3. Установка зависимостей приложения
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

# 4. Копируем остальной код и билдим
COPY . .
RUN yarn build

CMD ["node", "dist/main"]
