FROM mcr.microsoft.com/playwright:v1.45.0-jammy

# Только Chromium (без WebKit и Firefox)
RUN npx playwright install --with-deps chromium

WORKDIR /app

# Копируем только package.json и yarn.lock сначала — для кэширования
COPY package.json yarn.lock ./

# Установка Yarn (если нужно) и зависимостей
RUN npm install -g yarn \
    && yarn install

# Копируем остальной код
COPY . .

# Собираем проект
RUN yarn build

CMD ["node", "dist/main"]
