FROM node:22-slim

# 1. Установка зависимостей Playwright
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Установка playwright (включая Chromium/Firefox/Webkit)
RUN npm install -g yarn && \
    yarn add playwright && \
    npx playwright install --with-deps

WORKDIR /app

# 3. Копируем зависимости и устанавливаем их
COPY package.json yarn.lock ./
RUN yarn install

# 4. Копируем остальной проект и билдим
COPY . .
RUN yarn build

CMD ["node", "dist/main"]
