FROM mcr.microsoft.com/playwright:v1.45.0-jammy

WORKDIR /app

# Установим Node.js 20.18.1 вручную
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && node -v  # Проверим версию

COPY package.json yarn.lock ./
RUN npm install -g yarn && yarn install

COPY . .
RUN yarn build

CMD ["node", "dist/main"]
